name: Pull Request Validation

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, ready_for_review, review_requested]

permissions: write-all

jobs:
  checkout-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main code
        uses: actions/checkout@v4

      - name: Checkout templates
        uses: actions/checkout@v4
        with:
          repository: Cristian133/templates
          ref: main
          path: templates

      - name: Run Validation
        uses: ./
